version: @composeSyntaxVersion@

services:

  elasticsearch:
    image: ${DOCKER_ELASTIC_REGISTRY:-docker.elastic.co}/elasticsearch/elasticsearch:6.6.1
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - @proxyNetwork@
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"

  logstash:
    image: ${DOCKER_ELASTIC_REGISTRY:-docker.elastic.co}/logstash/logstash:6.4.3
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/config/logstash.conf
    command: -f /usr/share/logstash/config/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - @proxyNetwork@
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"

  kibana:
    image: ${DOCKER_ELASTIC_REGISTRY:-docker.elastic.co}/kibana/kibana:6.6.1
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - @proxyNetwork@
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=@proxyNetwork@"
        - "traefik.frontend.rule=Host:kibana.test"
        - "traefik.port=5601"

configs:

  elastic_config:
    file: ./configs/elasticsearch/elasticsearch.yml
  logstash_config:
    file: ./configs/logstash/logstash.yml
  logstash_pipeline:
    file: ./configs/logstash/logstash.conf
  kibana_config:
    file: ./configs/kibana/kibana.yml

networks:
  @proxyNetwork@:
    external: true
